qdrant:
  url: "${QDRANT_URL}"
  api_key: "${QDRANT_API_KEY}"
  use_grpc: true

embedding:
  primary:
    provider: "gemini"
    model: "gemini-embedding-001"
    api_key: "${GEMINI_API_KEY}"
    dimensions: 768

# Issue Triage Agent Configuration
triage:
  enabled: true
  llm:
    provider: "gemini"
    model: "gemini-1.5-flash"
    api_key: "${GEMINI_API_KEY}"
  classifier:
    enabled: true
    min_confidence: 0.7
    labels:
      - name: "bug"
        keywords: ["error", "crash", "broken", "not working", "fails", "exception"]
      - name: "enhancement"
        keywords: ["feature", "add", "improve", "request", "support for"]
      - name: "question"
        keywords: ["how to", "help", "?", "wondering", "example"]
      - name: "documentation"
        keywords: ["docs", "readme", "typo", "docstring", "api reference"]
      - name: "sdk/python"
        keywords: ["python", "pip", "pypi", "import nexusflow"]
      - name: "sdk/go"
        keywords: ["golang", "go mod", "go get", "nexusflow.NewClient"]
      - name: "sdk/typescript"
        keywords: ["typescript", "npm", "yarn", "javascript", "node"]
  quality:
    enabled: true
    min_score: 0.5
    needs_info_label: "needs-info"
  duplicate:
    enabled: true
    auto_close_threshold: 0.95
    require_confirmation: false

defaults:
  similarity_threshold: 0.65
  max_similar_to_show: 5
  include_closed_issues: true
  closed_issue_weight: 0.9
  cross_repo_search: true
  comment_cooldown_hours: 1
  delayed_actions:
    enabled: true
    delay_hours: 24
    approve_reaction: "+1"
    cancel_reaction: "-1"
    execute_on_approve: false

repositories:
  - org: "similigh"
    repo: "nexusflow-sdk"
    enabled: true
    similarity_threshold: 0.65

rate_limits:
  github_requests_per_second: 10
  embedding_requests_per_second: 5
  qdrant_requests_per_second: 50

repositories:
  - org: "similigh"
    repo: "nexusflow-sdk"
    enabled: true
    similarity_threshold: 0.65
    transfer_rules:
      # Documentation issues should go to docs repo
      - match:
          title_contains: ["documentation", "docs", "tutorial", "guide", "example"]
        target: "similigh/nexusflow-docs"
        priority: 1
      - match:
          body_contains: ["documentation", "missing docs", "add example", "API reference", "docs.nexusflow.io"]
        target: "similigh/nexusflow-docs"
        priority: 2
      - match:
          title_contains: ["search", "docs.nexusflow.io"]
        target: "similigh/nexusflow-docs"
        priority: 1
      - match:
          body_contains: ["docs.nexusflow.io", "documentation site", "doc site"]
        target: "similigh/nexusflow-docs"
        priority: 2

      # Core server issues go to core
      - match:
          title_contains: ["server bug", "gateway", "memory leak", "TLS", "WebSocket", "plugin"]
        target: "similigh/nexusflow-core"
        priority: 3
      - match:
          body_contains: ["server crash", "gateway error", "runtime panic", "server-side", "backend bug"]
        target: "similigh/nexusflow-core"
        priority: 4

      # CLI issues go to CLI
      - match:
          title_contains: ["CLI", "command line", "nexus deploy", "nexus login"]
        target: "similigh/nexusflow-cli"
        priority: 5

      # VS Code issues go to vscode
      - match:
          title_contains: ["VS Code", "VSCode", "extension", "IntelliSense"]
        target: "similigh/nexusflow-vscode"
        priority: 6
