qdrant:
  url: "${QDRANT_URL}"
  api_key: "${QDRANT_API_KEY}"
  use_grpc: true

embedding:
  primary:
    provider: "gemini"
    model: "gemini-embedding-001"
    api_key: "${GEMINI_API_KEY}"
    dimensions: 768

# Issue Triage Agent Configuration
triage:
  enabled: true
  llm:
    provider: "gemini"
    model: "gemini-2.5-flash-lite"
    api_key: "${GEMINI_API_KEY}"
  router:
    enabled: true
  classifier:
    enabled: true
    min_confidence: 0.7
    labels:
      - name: "bug"
        keywords: ["error", "crash", "broken", "not working", "fails", "exception"]
      - name: "enhancement"
        keywords: ["feature", "add", "improve", "request", "support for"]
      - name: "question"
        keywords: ["how to", "help", "?", "wondering", "example"]
      - name: "documentation"
        keywords: ["docs", "readme", "typo", "docstring", "api reference"]
      - name: "sdk/python"
        keywords: ["python", "pip", "pypi", "import nexusflow"]
      - name: "sdk/go"
        keywords: ["golang", "go mod", "go get", "nexusflow.NewClient"]
      - name: "sdk/typescript"
        keywords: ["typescript", "npm", "yarn", "javascript", "node"]
  quality:
    enabled: true
    min_score: 0.5
    needs_info_label: "needs-info"
  duplicate:
    enabled: true
    auto_close_threshold: 0.95
    require_confirmation: false

defaults:
  similarity_threshold: 0.65
  max_similar_to_show: 5
  include_closed_issues: true
  closed_issue_weight: 0.9
  cross_repo_search: true
  comment_cooldown_hours: 1
  delayed_actions:
    enabled: true
    delay_hours: 24
    approve_reaction: "+1"
    cancel_reaction: "-1"
    execute_on_approve: false
    optimistic_transfers: true

repositories:
  - org: "similigh"
    repo: "nexusflow-core"
    description: "The core engine of NexusFlow. Handles server-side logic, performance, security, and internal system bugs."
    enabled: true
  - org: "similigh"
    repo: "nexusflow-docs"
    description: "Public documentation for NexusFlow. Handles usage guides, API references, and documentation-related requests."
    enabled: true
  - org: "similigh"
    repo: "nexusflow-cli"
    description: "The command-line interface for NexusFlow. Handles 'nexus' command issues, deployment commands, and terminal output."
    enabled: true
  - org: "similigh"
    repo: "nexusflow-vscode"
    description: "The VS Code extension for NexusFlow. Handles IntelliSense, snippet support, and editor-specific bugs."
    enabled: true
  - org: "similigh"
    repo: "nexusflow-sdk"
    description: "The client SDKs for Go, Python, and TypeScript. Handles client-side libraries and integration logic."
    enabled: true

rate_limits:
  github_requests_per_second: 10
  embedding_requests_per_second: 5
  qdrant_requests_per_second: 50

# Pipeline Configuration (Execution Order)
pipeline:
  steps:
    - "gatekeeper"
    - "vectordb_prep"
    - "similarity_search"
    - "transfer_check"
    - "triage"
    - "response_builder"
    - "action_executor"
    - "indexer"
